### PR TITLE
Switch from jbuilder to dune and opam 2.0

### PR DESCRIPTION
**Pull request by kit-ty-kate**
Same as https://github.com/darioteixeira/ocaml-safepass/pull/10 (oops sorry @pveber I should've looked for PRs before starting) with:
* Upgrade to opam 2.0
* Safe-string related warnings removed

on top of the same upgrade to dune

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
cc @darioteixeira who doesn't seem to be watching this repository and might miss the notification. Just in case.

**Comment by darioteixeira** [comment]
Thanks @kit-ty-kate! The PR looks good. Also, I'll enable the notifications... ;-)

**Comment by pveber** [comment]
@kit-ty-kate No problem, your PR is more comprehensive than mine. Thanks!

**Comment by kit-ty-kate** [comment]
Would it be possible to get a new release of safepass by any chance?

**Pull request merged**
